Added php-fpm tasks defaults and templates
stuvusIT/php-fpm pull request #2
Opened 2017-04-10 17:39 UTC by Scriptkiddi

Added templates for pools and php fpm conf
tasks to setup all services and fill the templates with values

2017-04-12 15:42 UTC, SlothOfAnarchy requested changes

2017-04-12 15:42 UTC, SlothOfAnarchy commented on README.md
> +php_ini_values:
duplicate of the example below. what is this supposed to be?
Please explain your basic variable structure and list at least the mandatory vars.

2017-04-12 15:42 UTC, SlothOfAnarchy commented on tasks/main.yml
> +- name: Update repositories cache and install "php" package
`update_cache: yes` is missing or the name is wrong

2017-04-12 15:42 UTC, SlothOfAnarchy commented on tasks/main.yml
> +    block: |
what is the purpose of this pipe?

2017-04-12 15:42 UTC, SlothOfAnarchy commented on templates/php-fpm.conf.j2
> +{% if events.mechanism %}
you need to check if both events and events.mechanism is defined

2017-04-12 15:42 UTC, SlothOfAnarchy commented on defaults/main.yml
> +fpm_conf:
if you define it this way, you need to access all attributes by fpm_conf.*

2017-04-12 15:42 UTC, SlothOfAnarchy commented on README.md
> +# Role Name
your role name here

2017-04-12 15:42 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +listen.allowed_clients = {{ pool.listen.allowed_clients | default(allowed_clients) }}
default(allowed_clients) won't work. If listen is replaced and does not define allowed_clients, the attribute is missing

2017-04-12 15:42 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +{% if pool.listen.owner %}
check existence of all variable parts, here and further down

2017-04-12 15:42 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +listen.mode = {{ pool.listen.mode | default(listen.mode)}}
same thing here: default uses possibly not defined var

2017-04-12 15:42 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    group = pool.group
are you sure you can access it this way? please access the vars consistently, i.e. not mixing group and pool.group access patterns

2017-04-12 16:07 UTC, Scriptkiddi commented on defaults/main.yml
> +fpm_conf:
done

2017-04-12 16:25 UTC, Scriptkiddi commented on tasks/main.yml
> +    block: |
multiline var

2017-04-12 17:53 UTC, SlothOfAnarchy requested changes

2017-04-12 17:53 UTC, SlothOfAnarchy commented on README.md
> +| Name                      | Required                 | Description       |
your table is not displayed correctly in github

2017-04-12 17:53 UTC, SlothOfAnarchy commented on tasks/main.yml
> +    block: |
but it's only one line?

2017-04-12 17:53 UTC, SlothOfAnarchy commented on README.md
> +fpm_conf:
update example

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/php-fpm.conf.j2
> +syslog.facility = {{ daemon }}
use `syslog.facility` and check for existence

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/php-fpm.conf.j2
> +log_level = {{ notice }}
use `log_level`

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/php-fpm.conf.j2
> +syslog.ident = php-fpm
use `syslog.ident`

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +listen = {{ listen | mandatory }}
I think you mean `pool.listen`. Otherwise the dict listen dict will be inserted here

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    listen.backlog = {{- pool.listen.backlog -}}
what is the purpose of the dashes? same case a bit further down

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    listen.allowed_clients = {{- allowed_clients }}
`listen.allowed_clients` or check if it is defined

2017-04-12 17:53 UTC, SlothOfAnarchy commented on defaults/main.yml
> +listen.allowed_clients: any
`listen` could also be overridden and not define these three values. But I think it's okay to leave it like this. Same thing with `pm`

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +{% if pool.processes.priority is defined %}
check if `pool.processes` is defined

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    chroot = pool.chroot
{{ }}

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    slowlog = pool.slowlog
{{ }}

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    slowlog = slowlog
{{ }}

2017-04-12 17:53 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    clear_env = pool.clear_env
{{ }} *4

2017-04-13 09:43 UTC, Scriptkiddi commented on README.md
> +| Name                      | Required                 | Description       |
done

2017-04-13 09:45 UTC, Scriptkiddi commented on README.md
> +fpm_conf:
done

2017-04-13 09:48 UTC, Scriptkiddi commented on templates/php-fpm.conf.j2
> +syslog.facility = {{ daemon }}
done

2017-04-13 09:48 UTC, Scriptkiddi commented on templates/php-fpm.conf.j2
> +log_level = {{ notice }}
done

2017-04-13 09:48 UTC, Scriptkiddi commented on templates/php-fpm.conf.j2
> +syslog.ident = php-fpm
done

2017-04-13 09:50 UTC, Scriptkiddi commented on templates/pool.conf.j2
> +listen = {{ listen | mandatory }}
done

2017-04-13 09:50 UTC, Scriptkiddi commented on templates/pool.conf.j2
> +    listen.backlog = {{- pool.listen.backlog -}}
done

2017-04-13 09:52 UTC, Scriptkiddi commented on templates/pool.conf.j2
> +    listen.allowed_clients = {{- allowed_clients }}
done

2017-04-13 09:54 UTC, Scriptkiddi commented on templates/pool.conf.j2
> +{% if pool.processes.priority is defined %}
done

2017-04-13 10:06 UTC, SlothOfAnarchy requested changes

2017-04-13 10:06 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    {% if pool.processes.priority is defined %}
use `and`

2017-04-13 10:09 UTC, SlothOfAnarchy approved these changes

2017-04-13 10:09 UTC, merged