Dev
stuvusIT/php-fpm pull request #3
Opened 2017-04-15 14:19 UTC by Scriptkiddi

2017-04-15 16:19 UTC, SlothOfAnarchy requested changes

2017-04-15 16:19 UTC, SlothOfAnarchy commented on tasks/main.yml
> +  with_items:
why loop if you only install one package

2017-04-15 16:19 UTC, SlothOfAnarchy commented on tasks/main.yml
> +- name: "Update php.ini"
quotes are not necessary

2017-04-15 16:19 UTC, SlothOfAnarchy commented on templates/php-fpm.conf.j2
> +;# {{ ansible_managed }}
remove #

2017-04-15 16:19 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +;# {{ ansible_managed }}
remove #

2017-04-15 16:19 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +    pm.start_servers = {{ pool.pm.start_servers }}
please describe these vars in readme. The user can't even find them in the defaults.

2017-04-15 16:19 UTC, SlothOfAnarchy commented on templates/pool.conf.j2
> +{% if pool.slowlog is defined %}
why are using `is defined` all of the sudden? this use case should have worked before

2017-04-16 10:08 UTC, SlothOfAnarchy requested changes

2017-04-16 10:08 UTC, SlothOfAnarchy commented on README.md
> +    - 1
why is this a list?

2017-04-16 12:59 UTC, Scriptkiddi commented on templates/pool.conf.j2
> +    pm.start_servers = {{ pool.pm.start_servers }}
read the php_fpm doc for this

2017-04-16 13:00 UTC, Scriptkiddi commented on README.md
> +    - 1
because depending on what var you are setting multiple values are allowed and are merged by php into one var

2017-04-16 13:17 UTC, SlothOfAnarchy requested changes

2017-04-16 13:17 UTC, SlothOfAnarchy commented on README.md
> +    - 1
but this is not the case with `apc.enabled`?

2017-04-16 13:17 UTC, SlothOfAnarchy commented on README.md
>      pm: static
are you sure this works? you assign a string to `pm`, but then treat it as a dict

2017-04-17 21:36 UTC, SlothOfAnarchy approved these changes

2017-04-17 21:39 UTC, merged